### ISSUE TITLE
lost connection to rendering server

### ISSUE THREAD

**Issue by AnksioXD** [ThieuMinh26/Proot-Setup#21]
lost connection to rendering server on 8 read -1 22
Aborted

how do you fix this

**Comment by AnksioXD** [comment]
ok nevermind i was logging in using **proot-distro login ubuntu**, it was fixed by logging in using the **start** alias. which i think has **proot-distro login ubuntu --user root --shared-tmp**

**Comment by xDoge26** [comment]
yes `--shared-tmp` is required for virgl
