### ISSUE TITLE
chroot not running

### ISSUE THREAD

**Issue by Lsc0x80** [ThieuMinh26/Proot-Setup#28]
![IMG_20230827_131104](https://github.com/xDoge26/proot-setup/assets/101402482/556bab5e-0622-4854-b899-2d306c5edaa8)

**Comment by xDoge26** [comment]
What is your device info ?

**Comment by Lsc0x80** [comment]
snapdragon 732g
![IMG_20230827_222219](https://github.com/xDoge26/proot-setup/assets/101402482/b9ddc04b-4b5b-4ad5-b337-078d59092443)

**Comment by Lsc0x80** [comment]
![Screenshot_2023-08-27-22-23-21-801_ru andr7e deviceinfohw](https://github.com/xDoge26/proot-setup/assets/101402482/ba4fb7c0-1971-4696-b07b-19413970b60f)

**Comment by xDoge26** [comment]
can you try again ?

**Comment by Lsc0x80** [comment]
Everything started! but...

**Comment by Lsc0x80** [comment]
is that not your problem?
![Screenshot_2023-08-28-17-26-42-582_com termux](https://github.com/xDoge26/proot-setup/assets/101402482/8f9b1767-0b55-499f-b8b8-974856d907e4)
