### ISSUE TITLE
Name or service not known

### ISSUE THREAD

**Issue by Lsc0x80** [ThieuMinh26/Proot-Setup#29]
i have changed hostname in kernel
![Screenshot_2023-08-28-17-37-50-134_com termux](https://github.com/xDoge26/proot-setup/assets/101402482/cccf3e5f-3975-4ea8-95b3-7672092bd3fc)

**Comment by xDoge26** [comment]
Dont do funny thing with the kernel

**Comment by Lsc0x80** [comment]
why?bro

**Comment by xDoge26** [comment]
Because you will end up asking why x doesnt work , why y doesnt work ...
