### ISSUE TITLE
Package 'libodbc1:armhf' has no installation candidate  and Unable to locate package libtiff5:armhf when installing Box64/Box86

### ISSUE THREAD

**Issue by StevenBeach33** [ThieuMinh26/Proot-Setup#30]
![Screenshot_20231205-153531.png](https://github.com/xDoge26/proot-setup/assets/107557824/d7dd7cf8-6672-4789-8daf-13a54b1a70ea)

**Comment by Jacobw1oo** [comment]
run
wget https://github.com/xDoge26/proot-setup/raw/main/box86_64.sh 
nano box86_64.sh 
remove libtiff5:armhf, libjpeg8:armhf libtiff5:arm64 libjpeg8:arm64
save then run 
bash box86_64.sh 
rm box86_64.sh  (if you want)

suggest should fix libodbc1:armh. if not, run apt update.

**Comment by xDoge26** [comment]
yeah i dont have time to maintain the scripts sorry. Better use something else like mobox or whatever it called
