### ISSUE TITLE
Could not load kernel32.dll

### ISSUE THREAD

**Issue by mikamito998** [ThieuMinh26/Proot-Setup#4]
After install wine and start vnc and type box86 wine winecfg there is error : Could not load kernel32.dll

**Comment by ThieuMinh26** [comment]
Oh yes i faced that problem before , you can try replace wine amd64 with wine x86 , it fixed that problem https://github.com/Kron4ek/Wine-Builds/releases/tag/8.0 

Or ... you can disable selinux which is easier (but this method need root)

**Comment by mikamito998** [comment]
May I ask, what are you doing in future in this proot-setup project?

**Comment by ThieuMinh26** [comment]
Its just for fun , since android have a lots of limitation

**Comment by mikamito998** [comment]
This is a good project, because out there no one can install box64+wine on termux proot.  At that time I was having trouble installing wine on arm64 and I was happy when I found a youtube tutorial video that directed me here.

**Comment by ThieuMinh26** [comment]
> there no one can install box64+wine on termux proot

Actually there are many people who did that before me , they just dont want to make a tutorial :P

**Comment by ThieuMinh26** [comment]
And is the problem fixed ?

**Comment by mikamito998** [comment]
not solved, i think i need to change termux prefix to x86.

**Comment by ThieuMinh26** [comment]
i think you should try to replace wine-amd64 with wine-x86 . It fixed that problem (at least with me)

**Comment by mikamito998** [comment]
> > there no one can install box64+wine on termux proot
> 
> Actually there are many people who did that before me , they just dont want to make a tutorial :P

Yeah, that's kinda bad🥲

**Comment by ThieuMinh26** [comment]
Ok i reinstall termux and im have the same problem as you , im trying to fix it (without root method , with root you can disable selinux and the problem is fixed)

**Comment by mikamito998** [comment]
Thank you for trying to fix it🥰

**Comment by ThieuMinh26** [comment]
> Thank you for trying to fix it🥰

Can you try `WINEARCH=win32 box86 wine winecfg` ?

**Comment by mikamito998** [comment]
oot@localhost:~# WINEARCH=win32 box86 wine winecfg
Box86 with Dynarec v0.2.9 49c65078 built on Feb 23 2023 06:32:33
Box86 with Dynarec v0.2.9 49c65078 built on Feb 23 2023 06:32:33
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Cores:8
Params database has 15 entries
Box64 with Dynarec v0.2.1 1f9973e6 built on Feb 24 2023 07:18:56
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 45 Env var
Looking for /root/wine/bin/wineserver
Rename process to "wineserver"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
wine: WINEARCH set to win32 but '/root/.wine' is a 64-bit installation.
root@localhost:~# box86 wine winecfg
Box86 with Dynarec v0.2.9 49c65078 built on Feb 23 2023 06:32:33
Box86 with Dynarec v0.2.9 49c65078 built on Feb 23 2023 06:32:33
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Cores:8
Params database has 15 entries
Box64 with Dynarec v0.2.1 1f9973e6 built on Feb 24 2023 07:18:56
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 44 Env var
Looking for /root/wine/bin/wineserver
Rename process to "wineserver"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
002c:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
wine: could not load kernel32.dll, status c0000135

**Comment by mikamito998** [comment]
still could not load kernel32.dll 😭

**Comment by ThieuMinh26** [comment]
> still could not load kernel32.dll 😭

have you removed wine prefix first ?

**Comment by mikamito998** [comment]
> > still could not load kernel32.dll 😭
> 
> have you removed wine prefix first ?

Not yet. like this?
rm -r ~/.wine

**Comment by ThieuMinh26** [comment]
Yes you must remove broken wine prefix before creating a new one

**Comment by mikamito998** [comment]
Ok thx 🥰

**Comment by mikamito998** [comment]
where are you from?

**Comment by ThieuMinh26** [comment]
> Ok thx 🥰

and is the problem fixed ?

**Comment by mikamito998** [comment]
Sorry, I've been busy lately.  Yes it's fixed, thank you so much🥰
