### ISSUE TITLE
Zink not working

### ISSUE THREAD

**Issue by leem919** [ThieuMinh26/Proot-Setup#5]
When I try running a program with the zink alias, it crashes instantly and says `lost connection to rendering server on 8 read -1 104
Aborted`
Outside of the proot, it's saying `libEGL warning: MESA-LOADER: failed to open swrast: dlopen failed: cannot locate symbol "_ZN7android18egl_get_connectionEv" referenced by "/system/lib64/libGLESv3.so"... (search paths /data/data/com.termux/files/usr/lib/dri, suffix _dri)
failed to initialise renderer.`

**Comment by ThieuMinh26** [comment]
If you have adreno 640 . You should use turnip zink

**Comment by ThieuMinh26** [comment]
I only tested it with adreno 610

**Comment by ThieuMinh26** [comment]
idk

**Comment by ThieuMinh26** [comment]
Try this : 
https://github.com/termux/termux-packages/pull/15505#issue-1612779065

**Comment by ThieuMinh26** [comment]
> I switched out mesa in your script with Heasterian's mesa-turnip-kgsl, and got the same error. I tried using your new gles setup, and got `*** stack smashing detected ***: terminated Aborted` am I at a dead end here?

You can try 
`https://github.com/termux/termux-packages/pull/15505#issue-1612779065`

**Comment by ShapeShifter499** [comment]
@leem919 coming across this myself. Do you know what version of Ubuntu you installed?

**Comment by leem919** [comment]
22.04.2, it seems to be the default when just doing `proot-distro install ubuntu`
