### ISSUE TITLE
README Has no instructions

### ISSUE THREAD

**Issue by bornagainpenguin** [ThieuMinh26/Proot-Setup#6]
Expected to see a tutorial here but there does not seem to be one.

**Comment by xDoge26** [comment]
I dont have time to write it
You can watch : https://youtu.be/ykVd-67yMA0

**Comment by bornagainpenguin** [comment]
Following the video, the first part was without issues seemingly.  Then the second part gave me this:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package xfce4
E: Unable to locate package xfce4-terminal
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package adwaita-icon-theme-full
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package gnome-themes-extra
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
mkdir: cannot create directory ‘/data/data/com.termux/files/home/.vnc’: File exists
./Proot-Distro.sh: line 23: /usr/local/bin/vnc-start: No such file or directory
./Proot-Distro.sh: line 24: /usr/local/bin/vnc-stop: No such file or directory
chmod: cannot access '/usr/local/bin/vnc-start': No such file or directory
chmod: cannot access '/usr/local/bin/vnc-stop': No such file or directory
```

Granted this is with me running a script from the Android beta of emudeck on my Retroid Pocket 3+ which also uses termux.  I will reset the device and try again with a clean system.  Thank you for the directions to the video.

**Comment by xDoge26** [comment]
Please use termux from github ver  0.118.0

**Comment by bornagainpenguin** [comment]
**Please use termux from github ver 0.118.0**

Will do once I get it reset.  The installer for the emudeck for Android requires the earlier version installed.  I will install the latest version and reattempt the installer for proot and Box64.

**Comment by bornagainpenguin** [comment]
I have everything installed but I'm unable to tell from the video what VNC you're using.  I do not know of any VNC named address book.  Please advise.

**Comment by xDoge26** [comment]
https://play.google.com/store/apps/details?id=com.gaurav.avnc

https://play.google.com/store/apps/details?id=com.realvnc.viewer.android

**Comment by xDoge26** [comment]
Done
